def create_nfl_schedule():
    """
    Create a dictionary containing the 2024 NFL schedule for each team.
    Each team's schedule is represented as a dictionary with weeks as keys and opponents as values.
    """
    nfl_schedule = {
        'ARI': {'Week1': 'BUF', 'Week2': 'LAR', 'Week3': 'DET', 'Week4': 'WAS', 'Week5': 'SF', 'Week6': 'GB',
                'Week7': 'LAC', 'Week8': 'MIA', 'Week9': 'CHI', 'Week10': 'NYJ', 'Week11': 'BYE', 'Week12': 'SEA',
                'Week13': 'MIN', 'Week14': 'SEA', 'Week15': 'NE', 'Week16': 'CAR', 'Week17': 'LAR', 'Week18': 'SF'},
        'ATL': {'Week1': 'PIT', 'Week2': 'PHI', 'Week3': 'KC', 'Week4': 'NO', 'Week5': 'TB', 'Week6': 'CAR',
                'Week7': 'SEA', 'Week8': 'TB', 'Week9': 'DAL', 'Week10': 'NO', 'Week11': 'DEN', 'Week12': 'BYE',
                'Week13': 'LAC', 'Week14': 'MIN', 'Week15': 'LV', 'Week16': 'NYG', 'Week17': 'WAS', 'Week18': 'CAR'},
        'BAL': {'Week1': 'KC', 'Week2': 'LV', 'Week3': 'DAL', 'Week4': 'BUF', 'Week5': 'CIN', 'Week6': 'WAS',
                'Week7': 'TB', 'Week8': 'CLE', 'Week9': 'DEN', 'Week10': 'CIN', 'Week11': 'PIT', 'Week12': 'LAC',
                'Week13': 'PHI', 'Week14': 'BYE', 'Week15': 'NYG', 'Week16': 'PIT', 'Week17': 'HOU', 'Week18': 'CLE'},
        'BUF': {'Week1': 'ARI', 'Week2': 'MIA', 'Week3': 'JAX', 'Week4': 'BAL', 'Week5': 'HOU', 'Week6': 'NYJ',
                'Week7': 'TEN', 'Week8': 'SEA', 'Week9': 'MIA', 'Week10': 'IND', 'Week11': 'KC', 'Week12': 'BYE',
                'Week13': 'SF', 'Week14': 'LAR', 'Week15': 'DET', 'Week16': 'NE', 'Week17': 'NYJ', 'Week18': 'NE'},
        'CAR': {'Week1': 'NO', 'Week2': 'LAC', 'Week3': 'LV', 'Week4': 'CIN', 'Week5': 'CHI', 'Week6': 'ATL',
                'Week7': 'WAS', 'Week8': 'DEN', 'Week9': 'NO', 'Week10': 'NYG', 'Week11': 'BYE', 'Week12': 'KC',
                'Week13': 'TB', 'Week14': 'PHI', 'Week15': 'DAL', 'Week16': 'ARI', 'Week17': 'TB', 'Week18': 'ATL'},
        'CHI': {'Week1': 'TEN', 'Week2': 'HOU', 'Week3': 'IND', 'Week4': 'LAR', 'Week5': 'CAR', 'Week6': 'JAX',
                'Week7': 'BYE', 'Week8': 'WAS', 'Week9': 'ARI', 'Week10': 'NE', 'Week11': 'GB', 'Week12': 'MIN',
                'Week13': 'DET', 'Week14': 'SF', 'Week15': 'MIN', 'Week16': 'DET', 'Week17': 'SEA', 'Week18': 'GB'},
        'CIN': {'Week1': 'NE', 'Week2': 'KC', 'Week3': 'WAS', 'Week4': 'CAR', 'Week5': 'BAL', 'Week6': 'NYG',
                'Week7': 'CLE', 'Week8': 'PHI', 'Week9': 'LV', 'Week10': 'BAL', 'Week11': 'LAC', 'Week12': 'BYE',
                'Week13': 'PIT', 'Week14': 'DAL', 'Week15': 'TEN', 'Week16': 'CLE', 'Week17': 'DEN', 'Week18': 'PIT'},
        'CLE': {'Week1': 'DAL', 'Week2': 'JAX', 'Week3': 'NYG', 'Week4': 'LV', 'Week5': 'WAS', 'Week6': 'PHI',
                'Week7': 'CIN', 'Week8': 'BAL', 'Week9': 'LAC', 'Week10': 'BYE', 'Week11': 'NO', 'Week12': 'PIT',
                'Week13': 'DEN', 'Week14': 'PIT', 'Week15': 'KC', 'Week16': 'CIN', 'Week17': 'MIA', 'Week18': 'BAL'},
        'DAL': {'Week1': 'CLE', 'Week2': 'NO', 'Week3': 'BAL', 'Week4': 'NYG', 'Week5': 'PIT', 'Week6': 'DET',
                'Week7': 'BYE', 'Week8': 'SF', 'Week9': 'ATL', 'Week10': 'PHI', 'Week11': 'HOU', 'Week12': 'WAS',
                'Week13': 'NYG', 'Week14': 'CIN', 'Week15': 'CAR', 'Week16': 'TB', 'Week17': 'PHI', 'Week18': 'WAS'},
        'DEN': {'Week1': 'SEA', 'Week2': 'PIT', 'Week3': 'TB', 'Week4': 'NYJ', 'Week5': 'LV', 'Week6': 'LAC',
                'Week7': 'NO', 'Week8': 'CAR', 'Week9': 'BAL', 'Week10': 'KC', 'Week11': 'ATL', 'Week12': 'LV',
                'Week13': 'CLE', 'Week14': 'BYE', 'Week15': 'IND', 'Week16': 'LAC', 'Week17': 'CIN', 'Week18': 'KC'},
        'DET': {'Week1': 'LAR', 'Week2': 'TB', 'Week3': 'ARI', 'Week4': 'SEA', 'Week5': 'BYE', 'Week6': 'DAL',
                'Week7': 'MIN', 'Week8': 'TEN', 'Week9': 'GB', 'Week10': 'HOU', 'Week11': 'JAX', 'Week12': 'IND',
                'Week13': 'CHI', 'Week14': 'GB', 'Week15': 'BUF', 'Week16': 'CHI', 'Week17': 'SF', 'Week18': 'MIN'},
        'GB': {'Week1': 'PHI', 'Week2': 'IND', 'Week3': 'TEN', 'Week4': 'MIN', 'Week5': 'LAR', 'Week6': 'ARI',
               'Week7': 'HOU', 'Week8': 'JAX', 'Week9': 'DET', 'Week10': 'BYE', 'Week11': 'CHI', 'Week12': 'SF',
               'Week13': 'MIA', 'Week14': 'DET', 'Week15': 'SEA', 'Week16': 'NO', 'Week17': 'MIN', 'Week18': 'CHI'},
        'HOU': {'Week1': 'IND', 'Week2': 'CHI', 'Week3': 'MIN', 'Week4': 'JAX', 'Week5': 'BUF', 'Week6': 'NE',
                'Week7': 'GB', 'Week8': 'IND', 'Week9': 'NYJ', 'Week10': 'DET', 'Week11': 'DAL', 'Week12': 'TEN',
                'Week13': 'JAX', 'Week14': 'BYE', 'Week15': 'MIA', 'Week16': 'KC', 'Week17': 'BAL', 'Week18': 'TEN'},
        'IND': {'Week1': 'HOU', 'Week2': 'GB', 'Week3': 'CHI', 'Week4': 'PIT', 'Week5': 'JAX', 'Week6': 'TEN',
                'Week7': 'MIA', 'Week8': 'HOU', 'Week9': 'MIN', 'Week10': 'BUF', 'Week11': 'NYJ', 'Week12': 'DET',
                'Week13': 'NE', 'Week14': 'BYE', 'Week15': 'DEN', 'Week16': 'TEN', 'Week17': 'NYG', 'Week18': 'JAX'},
        'JAX': {'Week1': 'MIA', 'Week2': 'CLE', 'Week3': 'BUF', 'Week4': 'HOU', 'Week5': 'IND', 'Week6': 'CHI',
                'Week7': 'NE', 'Week8': 'GB', 'Week9': 'PHI', 'Week10': 'MIN', 'Week11': 'DET', 'Week12': 'BYE',
                'Week13': 'HOU', 'Week14': 'TEN', 'Week15': 'NYJ', 'Week16': 'LV', 'Week17': 'TEN', 'Week18': 'IND'},
        'KC': {'Week1': 'BAL', 'Week2': 'CIN', 'Week3': 'ATL', 'Week4': 'LAC', 'Week5': 'NO', 'Week6': 'BYE',
               'Week7': 'SF', 'Week8': 'LV', 'Week9': 'TB', 'Week10': 'DEN', 'Week11': 'BUF', 'Week12': 'CAR',
               'Week13': 'LV', 'Week14': 'LAC', 'Week15': 'CLE', 'Week16': 'HOU', 'Week17': 'PIT', 'Week18': 'DEN'},
        'LV': {'Week1': 'LAC', 'Week2': 'BAL', 'Week3': 'CAR', 'Week4': 'CLE', 'Week5': 'DEN', 'Week6': 'PIT',
               'Week7': 'LAR', 'Week8': 'KC', 'Week9': 'CIN', 'Week10': 'BYE', 'Week11': 'MIA', 'Week12': 'DEN',
               'Week13': 'KC', 'Week14': 'TB', 'Week15': 'ATL', 'Week16': 'JAX', 'Week17': 'NO', 'Week18': 'LAC'},
        'LAC': {'Week1': 'LV', 'Week2': 'CAR', 'Week3': 'PIT', 'Week4': 'KC', 'Week5': 'BYE', 'Week6': 'DEN',
                'Week7': 'ARI', 'Week8': 'NO', 'Week9': 'CLE', 'Week10': 'TEN', 'Week11': 'CIN', 'Week12': 'BAL',
                'Week13': 'ATL', 'Week14': 'KC', 'Week15': 'TB', 'Week16': 'DEN', 'Week17': 'NE', 'Week18': 'LV'},
        'LAR': {'Week1': 'DET', 'Week2': 'ARI', 'Week3': 'SF', 'Week4': 'CHI', 'Week5': 'GB', 'Week6': 'BYE',
                'Week7': 'LV', 'Week8': 'MIN', 'Week9': 'SEA', 'Week10': 'MIA', 'Week11': 'NE', 'Week12': 'PHI',
                'Week13': 'NO', 'Week14': 'BUF', 'Week15': 'SF', 'Week16': 'NYJ', 'Week17': 'ARI', 'Week18': 'SEA'},
        'MIA': {'Week1': 'JAX', 'Week2': 'BUF', 'Week3': 'SEA', 'Week4': 'TEN', 'Week5': 'NE', 'Week6': 'BYE',
                'Week7': 'IND', 'Week8': 'ARI', 'Week9': 'BUF', 'Week10': 'LAR', 'Week11': 'LV', 'Week12': 'NE',
                'Week13': 'GB', 'Week14': 'NYJ', 'Week15': 'HOU', 'Week16': 'SF', 'Week17': 'CLE', 'Week18': 'NYJ'},
        'MIN': {'Week1': 'NYG', 'Week2': 'SF', 'Week3': 'HOU', 'Week4': 'GB', 'Week5': 'NYJ', 'Week6': 'BYE',
                'Week7': 'DET', 'Week8': 'LAR', 'Week9': 'IND', 'Week10': 'JAX', 'Week11': 'TEN', 'Week12': 'CHI',
                'Week13': 'ARI', 'Week14': 'ATL', 'Week15': 'CHI', 'Week16': 'SEA', 'Week17': 'GB', 'Week18': 'DET'},
        'NE': {'Week1': 'CIN', 'Week2': 'SEA', 'Week3': 'NYJ', 'Week4': 'SF', 'Week5': 'MIA', 'Week6': 'HOU',
               'Week7': 'JAX', 'Week8': 'NYJ', 'Week9': 'TEN', 'Week10': 'CHI', 'Week11': 'LAR', 'Week12': 'MIA',
               'Week13': 'IND', 'Week14': 'BYE', 'Week15': 'ARI', 'Week16': 'BUF', 'Week17': 'LAC', 'Week18': 'BUF'},
        'NO': {'Week1': 'CAR', 'Week2': 'DAL', 'Week3': 'PHI', 'Week4': 'ATL', 'Week5': 'KC', 'Week6': 'TB',
               'Week7': 'DEN', 'Week8': 'LAC', 'Week9': 'CAR', 'Week10': 'ATL', 'Week11': 'CLE', 'Week12': 'BYE',
               'Week13': 'LAR', 'Week14': 'NYG', 'Week15': 'WAS', 'Week16': 'GB', 'Week17': 'LV', 'Week18': 'TB'},
        'NYG': {'Week1': 'MIN', 'Week2': 'WAS', 'Week3': 'CLE', 'Week4': 'DAL', 'Week5': 'SEA', 'Week6': 'CIN',
                'Week7': 'PIT', 'Week8': 'WAS', 'Week9': 'CAR', 'Week10': 'TB', 'Week11': 'TB', 'Week12': 'DAL',
                'Week13': 'GB', 'Week14': 'NO', 'Week15': 'BAL', 'Week16': 'ATL', 'Week17': 'IND', 'Week18': 'PHI'},
        'NYJ': {'Week1': 'SF', 'Week2': 'TEN', 'Week3': 'NE', 'Week4': 'DEN', 'Week5': 'MIN', 'Week6': 'BUF',
                'Week7': 'PIT', 'Week8': 'NE', 'Week9': 'HOU', 'Week10': 'ARI', 'Week11': 'IND', 'Week12': 'BYE',
                'Week13': 'SEA', 'Week14': 'MIA', 'Week15': 'JAX', 'Week16': 'LAR', 'Week17': 'BUF', 'Week18': 'MIA'},
        'PHI': {'Week1': 'GB', 'Week2': 'ATL', 'Week3': 'NO', 'Week4': 'TB', 'Week5': 'CLE', 'Week6': 'CLE',
                'Week7': 'NYG', 'Week8': 'CIN', 'Week9': 'JAX', 'Week10': 'DAL', 'Week11': 'WAS', 'Week12': 'LAR',
                'Week13': 'BAL', 'Week14': 'CAR', 'Week15': 'PIT', 'Week16': 'WAS', 'Week17': 'DAL', 'Week18': 'NYG'},
        'PIT': {'Week1': 'ATL', 'Week2': 'DEN', 'Week3': 'LAC', 'Week4': 'IND', 'Week5': 'DAL', 'Week6': 'LV',
                'Week7': 'NYJ', 'Week8': 'NYG', 'Week9': 'WAS', 'Week10': 'BAL', 'Week11': 'CLE', 'Week12': 'CIN',
                'Week13': 'CIN', 'Week14': 'CLE', 'Week15': 'PHI', 'Week16': 'BAL', 'Week17': 'KC', 'Week18': 'CIN'},
        'SF': {'Week1': 'NYJ', 'Week2': 'MIN', 'Week3': 'LAR', 'Week4': 'NE', 'Week5': 'ARI', 'Week6': 'SEA',
               'Week7': 'KC', 'Week8': 'DAL', 'Week9': 'TB', 'Week10': 'TB', 'Week11': 'SEA', 'Week12': 'GB',
               'Week13': 'BUF', 'Week14': 'CHI', 'Week15': 'LAR', 'Week16': 'MIA', 'Week17': 'DET', 'Week18': 'ARI'},
        'SEA': {'Week1': 'DEN', 'Week2': 'NE', 'Week3': 'MIA', 'Week4': 'DET', 'Week5': 'NYG', 'Week6': 'SF',
                'Week7': 'ATL', 'Week8': 'BUF', 'Week9': 'LAR', 'Week10': 'SF', 'Week11': 'SF', 'Week12': 'ARI',
                'Week13': 'NYJ', 'Week14': 'ARI', 'Week15': 'GB', 'Week16': 'MIN', 'Week17': 'CHI', 'Week18': 'LAR'},
        'TB': {'Week1': 'WAS', 'Week2': 'DET', 'Week3': 'DEN', 'Week4': 'PHI', 'Week5': 'ATL', 'Week6': 'NO',
               'Week7': 'BAL', 'Week8': 'ATL', 'Week9': 'KC', 'Week10': 'SF', 'Week11': 'NYG', 'Week12': 'NYG',
               'Week13': 'CAR', 'Week14': 'LV', 'Week15': 'LAC', 'Week16': 'DAL', 'Week17': 'CAR', 'Week18': 'NO'},
        'TEN': {'Week1': 'CHI', 'Week2': 'NYJ', 'Week3': 'GB', 'Week4': 'MIA', 'Week5': 'IND', 'Week6': 'BYE',
                'Week7': 'BUF', 'Week8': 'DET', 'Week9': 'NE', 'Week10': 'LAC', 'Week11': 'MIN', 'Week12': 'HOU',
                'Week13': 'WAS', 'Week14': 'JAX', 'Week15': 'CIN', 'Week16': 'IND', 'Week17': 'JAX', 'Week18': 'HOU'},
        'WAS': {'Week1': 'TB', 'Week2': 'NYG', 'Week3': 'CIN', 'Week4': 'ARI', 'Week5': 'CLE', 'Week6': 'BAL',
                'Week7': 'CAR', 'Week8': 'CHI', 'Week9': 'NYG', 'Week10': 'PIT', 'Week11': 'PHI', 'Week12': 'DAL',
                'Week13': 'TEN', 'Week14': 'PIT', 'Week15': 'NO', 'Week16': 'PHI', 'Week17': 'ATL', 'Week18': 'DAL'},
    }

    return nfl_schedule